djangoProject6/characters/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "characters"

urlpatterns = [
    path('',views.list, name='list_characters'),
    path('save', views.save, name='save_characters'),
    path('edit/<int:id>',views.edit, name='edit'),
    path('detail/<int:id>', views.detail, name='detail_characters'),
    path('punto_uno',views.puntoUno),

]

djangoProject6/djangoProject6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('characters/', include('characters.urls', namespace='characters')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangoProject6/characters/models.py
from django.db import models

class City(models.Model):
    name=models.CharField(max_length=100)
    lat=models.FloatField( )
    lon=models.FloatField()

    class Meta:
        db_table="cities"

class Universe(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=1000)
    foundation= models.DateTimeField()

    class Meta:
        db_table="universes"


class Power(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table="powers"

class Character(models.Model):

    universe=models.ForeignKey(Universe, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    path = models.FileField(upload_to="")
    create_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "characters"


class PowerCharacter(models.Model):
    power=models.ForeignKey(Power, on_delete=models.CASCADE)
    character=models.ForeignKey(Character, on_delete=models.CASCADE)
    level=models.FloatField()


    class Meta:
        db_table="powers_characters"

djangoProject6/characters/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from characters.models import Character, City, Universe


def list(request):
    print(request.method)
    list_=Character.objects.all()
    return  render(request, 'characters/index.html', {'list':list_})



def save(request):

    if "GET" == request.method:
        return render(request, 'characters/save.html')

    name_=request.POST["name"]
    description_=request.POST["description"]
    file=request.FILES["file"]
    city_= City.objects.get(id=1)
    universe_ = Universe.objects.get(id=1)
    character =Character(name=name_, description=description_, path=file, city=city_, universe=universe_)
    character.save()

    return redirect('characters:list_characters')


def detail(request,id):
    try:
        character= Character.objects.get(id=id)
    except Character.DoesNotExist:
        return HttpResponse("Not found register")
    return render(request, 'characters/detail.html',{"character":character})

def edit(request, id):
    return HttpResponse(id)



def puntoUno(request):
    list=Character.objects.filter(name__startswith='B')
    html= ""
    for character in list:
        html=html +character.name +"<br>"
    return HttpResponse(html)

djangoProject6/characters/templates/characters/detail.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/global-style.css" %}">
</head>
<body>

<header>
    <form id="form">
        <h1>Com<span class="red">ics</span></h1>
        <label for="search"></label><input type="text" id="search" class="search" placeholder="Search"/>
    </form>
</header>

<main>
    <div class="container-character">
        <div class="character-info">
            <div class="container-image">
              <a> <img src="/media/{{character.path}}"  alt={{item.name}}></a>
            </div>
            <div class="info text-white">
                <h1 class="text-white">{{ character.name }}</h1>
                <hr />
                <div  class="text-gray" id="description">
                    <h3 class="text-white">Descripción</h3>
                    <p class="text-gray">{{ character.description }}</p>
                </div>
                <div id="powers">
                    <h3 class="text-white">Poderes</h3>
                    <ul class="text-gray">
                        <li>Resistencia física</li>
                        <li>Fuerza</li>
                        <li>Agilidad</li>
                    </ul>
                </div>

                <div id="additional-info">
                    <div class="item-additional-info">
                        <span class="text-bold text-white">Fecha de aparición: </span><span class="text-gray">12/03/2008</span><br />
                    </div>
                    <div class="item-additional-info">
                        <span class="text-bold text-white">Ciudad: </span><span class="text-gray">New York</span><br />
                    </div>
                    <div class="item-additional-info">
                        <span class="text-bold text-white">Universo cinematográfico: </span><span class="text-gray">Marvel</span><br />
                    </div>
                </div>

                <div class="container-button">
                    <a class="general-button" href="index.html">Inicio</a>
                </div>
            </div>
        </div>
    </div>
</main>

</body>
</html>

djangoProject6/characters/templates/characters/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/global-style.css" %}">
</head>
<body>

<header>
    <form id="form">
        <h1>Com<span class="red">ics</span></h1>
        <label for="search"></label><input type="text" id="search" class="search" placeholder="Search"/>
    </form>
</header>

<main>
    <div class="container-universes">
        <button class="button">Marvel</button>
        <button class="button active">DC</button>
        <button class="button">Anime</button>
        <button class="button">Valiant</button>
    </div>

    <div class="container-items">
        {% for item in list %}
        <div class="item">
             <a href={% url 'characters:detail_characters' id=item.id %}>
                   <img src="/media/{{item.path}}"  alt={{item.name}}>
            </a>
            <div class="item-info">
                <h3>{{ item.name }}</h3>
                <span class="item-info">5.3</span>
            </div>
            <div class="overview">
                <h3>Descripción</h3>
                <p>{{ item.description }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</main>

<footer class="footer">
    <div class="footer__copy">
        <div class="footer__content">
            <div class="copy__text">
                © 2021 Jaider Pérez
            </div>
        </div>
    </div>
</footer>

</body>
</html>

djangoProject6/characters/templates/characters/save.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/global-style.css" %}">
</head>
<body>

<header>
    <form id="form">
        <h1>Com<span class="red">ics</span></h1>
        <label for="search"></label><input type="text" id="search" class="search" placeholder="Search"/>
    </form>
</header>

<main>

 <div class=form-group">

        <form action="{% url 'characters:save_characters' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label style="color:white;" for="">Name</label>
            <br>
            <input name="name" type="text">
            <br>
               <label style="color:white;"  for="">Description</label>
            <br>
            <textarea name="description" id="" cols="30" rows="10"></textarea>
            <br>
             <label style="color:white;"  for="">Image</label>
            <br>
            <input name="file" type="file">
            <br>

            <button  type="submit"> Save character</button>


        </form>

    </div>
</main>

<footer class="footer">
    <div class="footer__copy">
        <div class="footer__content">
            <div class="copy__text">
                © 2021 Jaider Pérez
            </div>
        </div>
    </div>
</footer>

</body>
</html>